# Params
@pipelineKey = 28760219-d984-42d0-aaf1-d6c55b3ebae5
@jobKey = 79c00d89-9fdf-457d-9104-e3c429487aff

@failedChildKey = c2956afa-2816-4751-a94c-4eeab5035bf6
### RUN_JOB
GET https://pipelines.prod.cloudaware.com/_pipeline/handleTask?
    ROUTE={%22headers%22:{%22Host%22:%22default.pipelines.cloudaware-vm.appspot.com%22},%22service%22:%22pipelines%22,%22version%22:%22default%22}&
    taskType=RUN_JOB&
    pipelineKey={{pipelineKey}}&
    ON_QUEUE=pipeline&
    key={{jobKey}}

<> 2025-06-23T205657.500.txt

### FINALIZE_JOB
GET https://pipelines.prod.cloudaware.com/_pipeline/handleTask?
    ROUTE={%22headers%22:{%22Host%22:%22default.pipelines.cloudaware-vm.appspot.com%22},%22service%22:%22pipelines%22,%22version%22:%22default%22}&
    taskType=FINALIZE_JOB&
    pipelineKey={{pipelineKey}}&
    ON_QUEUE=pipeline&
    key={{jobKey}}

<> 2025-06-24T203706.500.txt

### CANCEL_JOB
GET https://pipelines.prod.cloudaware.com/_pipeline/handleTask?
    ROUTE={%22headers%22:{%22Host%22:%22default.pipelines.cloudaware-vm.appspot.com%22},%22service%22:%22pipelines%22,%22version%22:%22default%22}&
    taskType=CANCEL_JOB&
    pipelineKey={{pipelineKey}}&
    ON_QUEUE=pipeline&
    key={{jobKey}}

### HANDLE_CHILD_EXCEPTION
GET https://pipelines.prod.cloudaware.com/_pipeline/handleTask?
    ROUTE={%22headers%22:{%22Host%22:%22default.pipelines.cloudaware-vm.appspot.com%22},%22service%22:%22pipelines%22,%22version%22:%22default%22}&
    taskType=HANDLE_CHILD_EXCEPTION&
    pipelineKey={{pipelineKey}}&
    ON_QUEUE=pipeline&
    key={{jobKey}}&
    failedChildKey={{failedChildKey}}

<> 2025-06-24T211725.500.txt
<> 2025-06-24T204756.500.txt

### DELETE_PIPELINE
GET https://pipelines.prod.cloudaware.com/_pipeline/handleTask?
    ROUTE={%22headers%22:{%22Host%22:%22default.pipelines.cloudaware-vm.appspot.com%22},%22service%22:%22pipelines%22,%22version%22:%22default%22}&
    taskType=DELETE_PIPELINE&
    pipelineKey={{pipelineKey}}&
    ON_QUEUE=pipeline&
    key={{jobKey}}