server:
  port : 8080

spring:
  application:
    name: server-ui

  profiles:
    default: local

  datasource:
    url: jdbc:postgresql://localhost:5432/task_tube
    username: admin
    password: 12345